.Dd March 4, 2014
.Dt LIFTOFFRC 5
.Os
.
.Sh NAME
.Nm liftoffrc
.Nd configuration for liftoff
.
.Sh DESCRIPTION
The
.Xr liftoff 1
Xcode configuration tool can be configured using a
.Pa .liftoffrc
file in your home directory, or the directory from which you are running
.Ic liftoff .
This is a YAML file that defines a set of keys and values for configuring
.Ic liftoff .
.Pp
.Ic liftoff
will use the value for a given key from
.Pa ./.liftoffrc ,
then
.Pa ~/.liftoffrc .
If it can't find a value in those files, it will use the default configuration.
.
.Sh USAGE
You can use the lookup order to improve the experience when creating new
projects. For example, you can set the
.Ic author
key inside
.Pa ~/.liftoffrc :
.Pp
.Dl author: Gordon Fontenot
.Pp
Now, any projects you create will have your name set as the author by default.
.Pp
You can also use local
.Nm
files to customize information at a higher level. For example, you can set the
.Ic company
key inside
.Pa ~/dev/work-projects/.liftoffrc :
.Pp
.Dl company: thoughtbot
.Pp
Now, whenever you create projects for work, the company name will default to
.Ic thoughtbot ,
and the author name will default to
.Ic Gordon Fontenot .
.Pp
You can continue to create these for any directory in order to tweak the
settings for projects created inside them. For example, I also have
.Ic company
set inside
.Pa ~/dev/personal/.liftoffrc :
.Pp
.Dl company: Gordon Fontenot
.Pp
I could also set the
.Ic warnings
key to enable different warnings based on client requirements, or personal
preference.
.
.Sh CONFIGURATION
.Bl -tag -width 10
.It Ic configure_git
type: boolean
.br
default:
.Ic true
.Pp
Create
.Ic .gitignore ,
.Ic .gitattributes ,
and initialize git repo if needed.
.It Ic warnings_as_errors
type: boolean
.br
default:
.Ic true
.Pp
Turn warnings into errors on release builds.
.It Ic run_script_phases
type: array
.br
default: See
.Sx SCRIPT PHASES
.Pp
Install the specified scripts as individual Run Script Build Phases. The
scripts that you want to add should be located inside either the local
.Pa .liftoff/templates/
directory, or the user's
.Pa ~/.liftoff/templates/
directory.
.Pp
Each item in the array should be a dictionary containing a single key/value
pair. The key for the dictionary will be used as the template script's name.
The value will be used as the name of the script phase inside Xcode.
.It Ic enable_static_analyzer
type: boolean
.br
default:
.Ic true
.Pp
Turn on the static analyzer for the project.
.It Ic indentation_level
type: integer
.br
default:
.Ic 4
.Pp
Set the indentation width on the project (in spaces).
.It Ic use_tabs
type: boolean
.br
default:
.Ic false
.Pp
Configure the project to use spaces or tabs for indentation. As everyone knows,
you should really be using spaces for indentation. If you prefer to be wrong,
however, you can change this configuration to use tabs in your project.
.Pp
Note that this does
.Em not
affect the default templates. If you choose to be incorrect with your
indentation settings, we recommend that you also override the default templates
in order to be consistently wrong.
.It Ic warnings
type: array
.br
default: See
.Sx WARNINGS
.Pp
Enable the provided warnings for the Application target. Set to
.Ic false
to prevent warnings from being set.
.It Ic application_target_groups
type: dictionary
.br
default: See
.Sx APPLICATION GROUPS
.Pp
Generate the provided directory and group structure for the main Application
Target.
.It Ic unit_test_target_groups
type: dictionary
.br
default: See
.Sx UNIT TEST GROUPS
.Pp
Generate the provided directory and group structure for the Unit Test target.
.It Ic project_name
type: string
.br
default: none
.Pp
Set the default value for the project name when generating new projects. Not
defined by default.
.It Ic company
type: string
.br
default: none
.Pp
Set the default value for the company name when generating new projects. Not
defined by default.
.It Ic company_identifier
type: string
.br
default: based on company name
.Pp
Set the default value for the company identifier when generating new projects.
Default value is the provided company name, downcased and stripped of special
characters. For example:
.Ic My Company Name!
becomes
.Ic com.mycompanyname .
.It Ic author
type: string
.br
default: Pulled from the
.Ic gecos
field in
.Xr passwd 5
.Pp
Set the default value for the author name when generating new projects. The
current user's name will be automatically set as the default.
.It Ic prefix
type: string
.br
default: none
.Pp
Set the default value for the project prefix when generating new projects. Not
enabled by default.
.El
.
.Sh SCRIPT PHASES
.Ic liftoff
installs a single Run Script Build Phase by default:
.Bd -literal
  - todo.sh: Warn for TODO and FIXME comments
.Ed
.Pp
This script turns any
.Ic TODO
or
.Ic FIXME
comments into warnings at compilation time.
.
.Sh WARNINGS
.Ic liftoff
enables a set of warnings by default:
.Bl -tag -width 10
.It Ic GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED
Warn if an aggregate or union initializer is not fully bracketed.
.It Ic GCC_WARN_MISSING_PARENTHESES
Warn if parentheses are omitted in certain contexts, such as when there is an
assignment in a context where a truth value is expected, or when operators are
nested whose precedence people often get confused about.
.It Ic GCC_WARN_ABOUT_RETURN_TYPE
Causes warnings to be emitted when a function with a defined return type (not
void) contains a return statement without a return-value.  Also emits a warning
when a function is defined without specifying a return type.
.It Ic GCC_WARN_SIGN_COMPARE
Warn when a comparison between signed and unsigned values could produce an
incorrect result when the signed value is converted to unsigned.
.It Ic GCC_WARN_CHECK_SWITCH_STATEMENTS
Warn whenever a switch statement has an index of enumeral type and lacks a case
for one or more of the named codes of that enumeration.
.It Ic GCC_WARN_UNUSED_FUNCTION
Warn whenever a static function is declared but not defined or a non-inline
static function is unused.
.It Ic GCC_WARN_UNUSED_LABEL
Warn whenever a label is declared but not used.
.It Ic GCC_WARN_UNUSED_VALUE
Warn whenever a statement computes a result that is explicitly not used.
.It Ic GCC_WARN_UNUSED_VARIABLE
Warn whenever a local variable or non-constant static variable is unused aside
from its declaration.
.It Ic GCC_WARN_SHADOW
Warn whenever a local variable shadows another local variable, parameter or
global variable or whenever a built-in function is shadowed.
.It Ic GCC_WARN_64_TO_32_BIT_CONVERSION
Warn if a value is implicitly converted from a 64 bit type to a 32 bit type.
.It Ic GCC_WARN_ABOUT_MISSING_FIELD_INITIALIZERS
Warn if a structure's initializer has some fields missing.
.It Ic GCC_WARN_ABOUT_MISSING_NEWLINE
Warn when a source file does not end with a newline.
.It Ic GCC_WARN_UNDECLARED_SELECTOR
Warn if a
.Ic @selector(...)
expression referring to an undeclared selector is found.
.It Ic GCC_WARN_TYPECHECK_CALLS_TO_PRINTF
Check calls to
.Xr printf 3
and
.Xr scanf 3 ,
etc., to make sure that the arguments supplied have types appropriate to the
format string specified, and that the conversions specified in the format
string make sense.
.It Ic GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS
Warn about the use of deprecated functions, variables, and types (as indicated
by the
.Ic deprecated
attribute).
.It Ic CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATION
Warn if an Objective-C class either subclasses a deprecated class or overrides
a method that has been marked deprecated.
.It Ic CLANG_WARN_OBJC_IMPLICIT_RETAIN_SEL
Warn about implicit retains of 'self' within blocks, which can create a
retain-cycle.
.It Ic CLANG_WARN_IMPLICIT_SIGN_CONVERSION
Warn about implicit integer conversions that change the signedness of an
integer value.
.It Ic CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION
Warn about various implicit conversions that can lose information or are
otherwise suspicious.
.It Ic CLANG_WARN_EMPTY_BODY
Warn about loop bodies that are suspiciously empty.
.It Ic CLANG_WARN_ENUM_CONVERSION
Warn about implicit conversions between different kinds of enum values.  For
example, this can catch issues when using the wrong enum flag as an argument to
a function or method.
.It Ic CLANG_WARN_INT_CONVERSION
Warn about implicit conversions between pointers and integers. For example,
this can catch issues when one incorrectly intermixes using
.Ic NSNumber*
and raw integers.
.It Ic CLANG_WARN_CONSTANT_CONVERSION
Warn about implicit conversions of constant values that cause the constant
value to change, either through a loss of precision, or entirely in its
meaning.
.El
.
.Sh APPLICATION GROUPS
.Ic liftoff
creates a default directory and group structure for the main
application target that mimics the following structure:
.Pp
.Bd -literal
  - <%= project_name %>:
    - Categories:
    - Classes:
      - Controllers:
      - DataSources:
      - Delegates:
        - <%= prefix %>AppDelegate.h
        - <%= prefix %>AppDelegate.m
      - Models:
      - ViewControllers:
      - Views:
    - Constants:
    - Resources:
      - Images.xcassets
      - Storyboards:
      - Nibs:
      - Other-Sources:
        - <%= project_name %>-Info.plist
        - <%= project_name %>-Prefix.pch
        - main.m
.Ed
.Pp
It also generates templates for the
.Ic AppDelegate
class (appending the proper prefix), as well as
.Ic Info.plist,
.Ic Prefix.pch,
and
.Ic main.m
files. The
.Ic Info.plist
and
.Ic Prefix.pch
will be prepended with the project name.
.
.Sh UNIT TEST GROUPS
.Ic liftoff
creates a default directory and group structure for the unit test
target that mimics the following structure:
.Pp
.Bd -literal
  - UnitTests:
    - Resources:
      - UnitTests-Info.plist
      - UnitTests-Prefix.pch
    - Tests:
.Ed
.Pp
.Ic liftoff
will also generate templates for the
.Ic UnitTests-Info.plist
and
.Ic UnitTests-Prefix.pch
files.
.
.Sh FILES
.Pa ~/.liftoffrc
.
.Sh SEE ALSO
.Xr liftoff 1
.
.Sh AUTHORS
.An "Gordon Fontenot" Aq gordon@thoughtbot.com
and
.Lk http://thoughtbot.com thoughtbot
