source 'https://github.com/CocoaPods/Specs'

platform :ios, '<%= deployment_target %>'

# Add Application pods here

target :unit_tests, :exclusive => true do
  link_with '<%= test_target_name %>'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
  pod 'OHHTTPStubs'
end
